### ISSUE TITLE
#line failed

### ISSUE THREAD

**Issue by psmathers** [learn-co-curriculum/deli-counter#12]
My method failed, but I think it's correct as is:

def line(katz_deli)
  if katz_deli.length == 0
    puts "The line is currently empty."
  else
    print "The line is currently: "
    katz_deli.each_with_index do |name, index|
      print "#{index+1}. #{name}  "
    end
    puts
  end
end

**Comment by AnnJohn** [comment]
hi @psmathers could you use the Ask a Question tool and someone from our Learn team will get back to you? Thanks!
