### ISSUE TITLE
difference in task example and spec expectation

### ISSUE THREAD

**Issue by nothingisfunny** [learn-co-curriculum/deli-counter#13]
Hi! The example provided in the task itself says method "take_a_number" should return the following:
take_a_number(katz_deli, "Matz") #=> 3
However, spec expects the following: "expect($stdout).to receive(:puts).with("Welcome, Ada. You are number 1 in line.")"
Probably, the task's example should be corrected.

**Comment by pletcher** [comment]
Fixed with https://github.com/learn-co-curriculum/deli-counter/commit/7503c9e494703fa96018df6d366d3ee3c1d58f3d
