### ISSUE TITLE
Submitted a suggested edit for the Deli Counter Lab instructions

### ISSUE THREAD

**Issue by dvimont** [learn-co-curriculum/deli-counter#16]
I just submitted a suggested edit to the Deli Counter Lab instructions (in the "README.md" file). This is my first time to submit a suggested change to text in a lesson, so I wanted to be sure I've followed appropriate procedures: I simply clicked the "Edit Lesson' button at the top of the page, made the changes, and clicked submit. I presume this may have resulted in a pull request being automatically issued in the background?

My edit was basically to add missing instructions regarding what should be returned by the #take_a_number method and the #now_serving method.

Thanks!!

**Comment by Joll59** [comment]
@dvimont thank you, That is the proper process for suggesting edits. I will take a look at the pull request. 

Closing issue.
