### ISSUE TITLE
The instructions for #take_a_number are incomplete.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/deli-counter#21]
Hello! The instructions for #take_a_number currently say that the method should accept two arguments: the array for the current line of people and the string with the name of the person who wants to join the line. They also mention that #take_a_number should "puts" the person's name and their position in line.

This is good, but the instructions ALSO need to mention that #take_a_number should add the person to the end of the line. Otherwise, the program won't work as intended, and the tests won't pass.

Thanks for looking into this!
Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
