### ISSUE TITLE
Pull Request Issue 

### ISSUE THREAD

**Issue by LesOsorio** [learn-co-curriculum/deli-counter#22]
After passing the lab I tried to submit pull request, but it didn't work. I tried refreshing my page, and even closed the IDE completely and tried submitting pull request again, but nothing.

**Comment by drakeltheryuujin** [comment]
Hi @LesOsorio, 

This request sounds like an issue with the Learn platform. [Raising issues on GitHub][raise] should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

If Learn is misbehaving, please direct your bug report to bugs@learn.co. If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
